import { readFileSync } from "node:fs";
import { pairedEffect } from "./epistemic-analysis.ts";
import { exactUpperSignFlipMitm } from "./epistemic-reward-confirmatory.ts";
import type { CrowdingArm, CrowdingReport, CrowdingRun } from "./welfare-crowding-out.ts";

type Mechanism = { hhMeetings:number;hhSwaps:number;hardAssignments:number;hardSolved:number;easyToHardGifts:number;hardToEasyGifts:number;easyToEasyGifts:number;allTransfers:number };
function mechanism(run:CrowdingRun):Mechanism{const out:Mechanism={hhMeetings:0,hhSwaps:0,hardAssignments:0,hardSolved:0,easyToHardGifts:0,hardToEasyGifts:0,easyToEasyGifts:0,allTransfers:0};for(const round of run.result.rounds){for(let id=0;id<round.types.length;id++)if(round.types[id]==="H"){out.hardAssignments++;out.hardSolved+=Number(round.solved[id]);}for(const meeting of round.meetings){const pair=[meeting.iType,meeting.jType].sort().join("");if(meeting.kind!=="none")out.allTransfers++;if(pair==="HH"){out.hhMeetings++;out.hhSwaps+=Number(meeting.kind==="swap");}if(meeting.kind==="gift"&&pair==="EH"){const sellerType=meeting.seller===meeting.i?meeting.iType:meeting.jType;if(sellerType==="E")out.easyToHardGifts++;else out.hardToEasyGifts++;}if(meeting.kind==="gift"&&pair==="EE")out.easyToEasyGifts++;}}return out;}
function sum(rows:Mechanism[],key:keyof Mechanism):number{return rows.reduce((total,row)=>total+row[key],0)}
function paired(report:CrowdingReport,key:"hhSwapRate"|"hardSolveRate"){const values=report.seeds.map(seed=>{const get=(arm:CrowdingArm)=>mechanism(report.runs.find(run=>run.seed===seed&&run.arm===arm)!);const gift=get("gift-talk"),money=get("money-talk");const rate=(row:Mechanism)=>key==="hhSwapRate"?row.hhSwaps/row.hhMeetings:row.hardSolved/row.hardAssignments;return rate(gift)-rate(money)});return{...pairedEffect(values),exactUpperP:exactUpperSignFlipMitm(values,0),values};}
const report=JSON.parse(readFileSync(process.argv[2]??"src/data/welfare-crowding-out.json","utf8")) as CrowdingReport;
const byArm=Object.fromEntries(report.arms.map(arm=>{const rows=report.runs.filter(run=>run.arm===arm).map(mechanism);return[arm,{hhSwaps:sum(rows,"hhSwaps"),hhMeetings:sum(rows,"hhMeetings"),hhSwapRate:sum(rows,"hhSwaps")/sum(rows,"hhMeetings"),hardSolved:sum(rows,"hardSolved"),hardAssignments:sum(rows,"hardAssignments"),hardSolveRate:sum(rows,"hardSolved")/sum(rows,"hardAssignments"),easyToHardGifts:sum(rows,"easyToHardGifts"),hardToEasyGifts:sum(rows,"hardToEasyGifts"),easyToEasyGifts:sum(rows,"easyToEasyGifts"),allTransfers:sum(rows,"allTransfers")}]}));
const totalWelfareGain=report.effects.giftMinusMoneyScore!.mean*report.seeds.length*8;const additionalHardSolves=(byArm["gift-talk"]!.hardSolved-byArm["money-talk"]!.hardSolved);const hardSolvePointGain=additionalHardSolves*3;
console.log("POST-HOC DESCRIPTIVE MECHANISM AUDIT — NOT A FROZEN MEDIATION TEST");console.log(JSON.stringify({byArm,paired:{giftMinusMoneyHhSwapRate:paired(report,"hhSwapRate"),giftMinusMoneyHardSolveRate:paired(report,"hardSolveRate")},welfareAccounting:{totalWelfareGain,additionalHardSolves,hardSolvePointGain,netCheckSalvageChange:totalWelfareGain-hardSolvePointGain}},null,2));
