import type { CalibrationReport } from "./calibrate.ts";
import type { Phase0Report } from "./phase0.ts";
import type { Phase1Report } from "./phase1.ts";
import type { Layer4Report } from "./layer4.ts";
import type { HysteresisReport } from "./hysteresis.ts";
import type { MinorityReport } from "./minority.ts";
import type { ChannelBReport } from "./channelb.ts";
import type { MixedReport } from "./mixed.ts";
import type { CkReport } from "./ck.ts";
import type { UnconfoundReport } from "./unconfound.ts";
import type { SpeechReport } from "./speech.ts";
import type { InvasionReport } from "./invasion.ts";
import type { DominatedReport } from "./dominated.ts";
import type { BeliefReport } from "./beliefs.ts";
import type { MemorylessReport } from "./memoryless.ts";
import type { OriginReport } from "./origination.ts";
import calibrationJson from "../../data/calibration.json";
import phase0Json from "../../data/phase0.json";
import phase1Json from "../../data/phase1.json";
import layer4Json from "../../data/layer4.json";
import hysteresisJson from "../../data/hysteresis.json";
import minorityJson from "../../data/minority.json";
import channelbJson from "../../data/channelb.json";
import mixedJson from "../../data/mixed.json";
import ckJson from "../../data/ck.json";
import unconfoundJson from "../../data/unconfound.json";
import speechJson from "../../data/speech.json";
import invasionJson from "../../data/invasion.json";
import dominatedJson from "../../data/dominated.json";
import beliefsJson from "../../data/beliefs.json";
import memorylessJson from "../../data/memoryless.json";
import originationJson from "../../data/origination.json";

export const calibration = calibrationJson as unknown as CalibrationReport;
export const phase0 = phase0Json as unknown as Phase0Report;
export const phase1 = phase1Json as unknown as Phase1Report;
export const layer4 = layer4Json as unknown as Layer4Report;
export const hysteresis = hysteresisJson as unknown as HysteresisReport;
export const minority = minorityJson as unknown as MinorityReport;
export const channelb = channelbJson as unknown as ChannelBReport;
export const mixed = mixedJson as unknown as MixedReport;
export const ck = ckJson as unknown as CkReport;
export const unconfound = unconfoundJson as unknown as UnconfoundReport;
export const speech = speechJson as unknown as SpeechReport;
export const invasion = invasionJson as unknown as InvasionReport;
export const dominated = dominatedJson as unknown as DominatedReport;
export const beliefs = beliefsJson as unknown as BeliefReport;
export const memoryless = memorylessJson as unknown as MemorylessReport;
export const origination = originationJson as unknown as OriginReport;
