import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { ACTION_TRANSFER_ARMS, actionTransferCost, actionTransferObject, actionTransferOrder, actionTransferPrompt, buildActionTransferReport, optimalPublish, parseActionTransfer, sha256ActionTransfer, type ActionTransferArm, type ActionTransferCaseResult } from "./founder-posterior-action-transfer.ts";
import { POSTERIOR_CASES, posteriorTruth } from "./founder-posterior-update.ts";

function fakeCase(caseId: number, choice: (arm: ActionTransferArm) => boolean): ActionTransferCaseResult { const item = POSTERIOR_CASES[caseId - 1]!, order = [...actionTransferOrder(caseId)]; return { caseId, case: item, calls: 3, apiFails: 0, parseFails: 0, order, observations: order.map((arm, index) => ({ arm, position: index + 1, promptHash: sha256ActionTransfer(actionTransferPrompt(arm, item)), decisionObject: actionTransferObject(arm, item), publish: choice(arm) })) }; }

describe("typed posterior to action transfer", () => {
  it("constructs a strict threshold between prior and posterior", () => { for (const item of POSTERIOR_CASES) { const threshold = actionTransferCost(item) / 2, posterior = posteriorTruth(item); assert.ok((item.prior < threshold && threshold < posterior) || (posterior < threshold && threshold < item.prior)); assert.notEqual(optimalPublish(actionTransferObject("prior-only", item)), optimalPublish(actionTransferObject("typed-posterior", item))); assert.equal(optimalPublish(actionTransferObject("prior-only", item)), optimalPublish(actionTransferObject("noninformative-control", item))); } });
  it("balances all three arms over call positions", () => { for (const arm of ACTION_TRANSFER_ARMS) assert.deepEqual([0, 1, 2].map((position) => POSTERIOR_CASES.filter((item) => actionTransferOrder(item.caseId)[position] === arm).length), [8, 8, 8]); });
  it("uses recommendation-free canonical objects", () => { for (const arm of ACTION_TRANSFER_ARMS) { const prompt = actionTransferPrompt(arm, POSTERIOR_CASES[0]!); assert.match(prompt, /expectedNetPublish/); assert.doesNotMatch(prompt, /recommendedAction/); } });
  it("parses a strict boolean action", () => { assert.equal(parseActionTransfer('{"publish":true}'), true); assert.throws(() => parseActionTransfer('{"publish":1}'), /schema/); assert.throws(() => parseActionTransfer('{"publish":true,"why":"x"}'), /schema/); });
  it("supports clean posterior-driven flips", () => { const cases = POSTERIOR_CASES.map((item) => fakeCase(item.caseId, (arm) => optimalPublish(actionTransferObject(arm, item)))); const report = buildActionTransferReport(cases, "test"); assert.equal(report.verdict, "POSTERIOR-TO-ACTION TRANSFER SUPPORTED"); assert.equal(report.typedFlipRate, 1); assert.equal(report.noninformativeStability, 1); assert.ok(Object.values(report.gates).every(Boolean)); });
  it("detects an ignored posterior", () => { const cases = POSTERIOR_CASES.map((item) => fakeCase(item.caseId, () => optimalPublish(actionTransferObject("prior-only", item)))); assert.equal(buildActionTransferReport(cases, "test").verdict, "POSTERIOR IGNORED OR MISAPPLIED"); });
  it("rejects corrupted payoff objects", () => { const result = fakeCase(1, () => true); result.observations[0]!.decisionObject.expectedNetPublish += 1; assert.throws(() => buildActionTransferReport([result], "test"), /decision object mismatch|arithmetic/); });
});
