import { runPopulationAsyncPaired } from "./env.ts";
import { coordinationSlice, structuralScheduleHash } from "./epistemic.ts";
import { grokChat, parseProposal } from "./llm.ts";
import { DEFAULT_PARAMS } from "./params.ts";
import { TURNOVER_FIRST_ROUND, TURNOVER_LAST_ROUND, replacementOrder } from "./persistence.ts";
import { meetingPrompt, RULES } from "./prompts.ts";
import type { AgentState, Proposal } from "./types.ts";
import { ENFORCEMENT_WINDOW, enforcementNotice, executedProposal, strictAction, type EnforcementArm, type EnforcementRun, type ProposalTrace, type ProposedSlice } from "./model-preserving-enforcement.ts";

const PARAMS={...DEFAULT_PARAMS,K:3};
function proposedSlice(trace:ProposalTrace[]):ProposedSlice { let he=0,seller=0,buyer=0,joint=0;for(const e of trace.filter(x=>x.t>=ENFORCEMENT_WINDOW.first&&x.t<=ENFORCEMENT_WINDOW.last&&x.meType==="E"&&x.partnerType==="H")){he++;const s=e.original.giveCheck&&e.original.requireChit;const h=trace.find(x=>x.t===e.t&&x.meId===e.partnerId&&x.partnerId===e.meId);if(!h)throw new Error("missing paired proposal trace");const b=h.original.giveChits===1;seller+=Number(s);buyer+=Number(b);joint+=Number(s&&b);}return{heMeetings:he,sellerIntent:seller,buyerIntent:buyer,jointIntent:joint,sellerIntentPerHe:he?seller/he:0,buyerIntentPerHe:he?buyer/he:0,jointIntentPerHe:he?joint/he:0};}

export async function runEnforcementCell(arm:EnforcementArm,seed:number):Promise<EnforcementRun>{const order=replacementOrder(seed);const replaced=new Set<number>();const trace:ProposalTrace[]=[];let calls=0,apiFails=0,parseFails=0;const before=(agents:AgentState[],t:number)=>{if(t>=TURNOVER_FIRST_ROUND&&t<=TURNOVER_LAST_ROUND){const id=order[t-TURNOVER_FIRST_ROUND]!;replaced.add(id);agents[id]!.memory=[];}};const decide=async(me:AgentState,partner:AgentState,t:number):Promise<Proposal>=>{calls++;const response=await grokChat({prompt:meetingPrompt(me,partner,t,PARAMS,"label",enforcementNotice(arm)),system:RULES,maxTokens:64,temperature:0,json:true});if(!response.ok){apiFails++;throw new Error(`enforcement ${arm} seed=${seed} t=${t} agent=${me.id}: ${response.error}`);}const invalid=strictAction(response.text);if(invalid){parseFails++;throw new Error(`enforcement ${arm} seed=${seed} t=${t} agent=${me.id}: ${invalid}; raw=${response.text.slice(0,180)}`);}const original=parseProposal(response.text);const out=executedProposal(arm,t,me.type,partner.type,me.checks,me.chits,partner.checks,partner.chits,original);trace.push({t,meId:me.id,partnerId:partner.id,meType:me.type,partnerType:partner.type,meChecks:me.checks,meChits:me.chits,partnerChecks:partner.checks,partnerChits:partner.chits,original,executed:out.proposal,eligible:out.eligible,overridden:out.overridden});return out.proposal;};const result=await runPopulationAsyncPaired(seed,decide,PARAMS,true,undefined,before);trace.sort((a,b)=>a.t-b.t||a.meId-b.meId||a.partnerId-b.partnerId);const executed=coordinationSlice(result,()=>true,ENFORCEMENT_WINDOW.first,ENFORCEMENT_WINDOW.last);const eligibleMeetings=trace.filter(x=>x.t>=ENFORCEMENT_WINDOW.first&&x.t<=ENFORCEMENT_WINDOW.last&&x.meType==="E"&&x.eligible).length;const enforcedTrades=result.rounds.flatMap(r=>r.meetings).filter(m=>m.t>=ENFORCEMENT_WINDOW.first&&m.t<=ENFORCEMENT_WINDOW.last&&m.kind==="chit-for-check").length;const transformFidelity=arm==="ledger-only"?trace.every(x=>!x.overridden&&JSON.stringify(x.original)===JSON.stringify(x.executed)):trace.every(x=>{const q=executedProposal(arm,x.t,x.meType,x.partnerType,x.meChecks,x.meChits,x.partnerChecks,x.partnerChits,x.original);return q.eligible===x.eligible&&q.overridden===x.overridden&&JSON.stringify(q.proposal)===JSON.stringify(x.executed);});const fidelity=transformFidelity&&(arm==="ledger-only"||enforcedTrades===eligibleMeetings);return{arm,seed,calls,apiFails,parseFails,robotCalls:0,scheduleHash:structuralScheduleHash(result),replacementOrder:order,notice:enforcementNotice(arm),trace,executed,proposed:proposedSlice(trace),eligibleMeetings,enforcedTrades,overrideFidelity:fidelity,meanScore:result.meanScore,result};}

export function printEnforcementDryRun():void {const me:AgentState={id:2,type:"E",checks:1,chits:0,score:20,solved:true,receivedFrom:null,memory:[]};const p:AgentState={...me,id:5,type:"H",chits:1,solved:false};for(const arm of ["ledger-only","blind-execution","disclosed-execution"] as const)console.log(`\n=== ${arm} ===\n${meetingPrompt(me,p,17,PARAMS,"label",enforcementNotice(arm))}`);}
