import { createHash } from "node:crypto";
import { existsSync,mkdirSync,readFileSync,writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { hasChatApiKey,LLM_CONFIG } from "./llm.ts";
import { printRoleChannelDryRun,runRoleChannelCell } from "./welfare-role-channel-execution.ts";
import { ROLE_CHANNEL_ARMS,ROLE_CHANNEL_SEEDS,buildRoleChannelReport,roleChannelOrder,type RoleChannelReport,type RoleChannelRun } from "./welfare-role-channel.ts";

const DATA="src/data/welfare-role-channel.json",PUBLIC="public/data/welfare-role-channel.json",FREEZE="src/data/welfare-role-channel-freeze.json",HEALTH="src/data/provider-health-welfare-role-channel.json";
type Manifest={model:string;targetCallsAtFreeze:0;files:Record<string,{path:string;sha256:string}>;dryRunSha256:string};
function hash(value:string|Uint8Array):string{return createHash("sha256").update(value).digest("hex");}
function validateFreeze(checkModel:boolean):void{const manifest=JSON.parse(readFileSync(FREEZE,"utf8")) as Manifest;if(checkModel&&manifest.model!==LLM_CONFIG.model)throw new Error(`freeze model mismatch ${manifest.model} != ${LLM_CONFIG.model}`);for(const [name,item] of Object.entries(manifest.files)){const actual=hash(readFileSync(resolve(item.path)));if(actual!==item.sha256)throw new Error(`freeze mismatch ${name}: ${actual} != ${item.sha256}`);}}
function load():RoleChannelRun[]{if(!existsSync(DATA))return[];const report=JSON.parse(readFileSync(DATA,"utf8")) as RoleChannelReport;if(report.model!==LLM_CONFIG.model)throw new Error(`model mismatch ${report.model}`);return report.runs;}
function bracketValidity():boolean|null{if(!existsSync(HEALTH))return null;const stored=JSON.parse(readFileSync(HEALTH,"utf8")) as {comparison?:{bracketValid?:boolean}};return typeof stored.comparison?.bracketValid==="boolean"?stored.comparison.bracketValid:null;}
function write(runs:RoleChannelRun[]):void{mkdirSync("src/data",{recursive:true});mkdirSync("public/data",{recursive:true});const value=JSON.stringify(buildRoleChannelReport(runs,LLM_CONFIG.model,bracketValidity()),null,2);writeFileSync(DATA,value);writeFileSync(PUBLIC,value);}
function requireHealthyOpenBracket(hasPendingCalls:boolean):void{if(!existsSync(HEALTH))throw new Error(`missing frozen pre-flight bracket ${HEALTH}`);const stored=JSON.parse(readFileSync(HEALTH,"utf8")) as {plan?:{studyId?:string;requestedModel?:string};pre?:{healthy?:boolean};eraBaselineCheck?:{passed?:boolean};post?:unknown};if(stored.plan?.studyId!=="VBE-W-RG-ROLE-GENERALIZATION-CHANNEL"||stored.plan.requestedModel!==LLM_CONFIG.model||!stored.pre?.healthy||!stored.eraBaselineCheck?.passed)throw new Error("provider-health pre-flight did not authorize this study/model");if(hasPendingCalls&&stored.post)throw new Error("post-flight already exists while target calls remain incomplete");}
const dry=process.argv.includes("--dry-run");validateFreeze(!dry);if(dry){printRoleChannelDryRun();process.exit(0);}if(!hasChatApiKey())throw new Error(`${LLM_CONFIG.apiKeyEnv} missing`);const runs=load(),done=new Set(runs.map(r=>`${r.seed}|${r.arm}`));requireHealthyOpenBracket(runs.length<48);console.log(`resume target=${runs.length}/48`);for(const seed of ROLE_CHANNEL_SEEDS)for(const arm of roleChannelOrder(seed)){const key=`${seed}|${arm}`;if(done.has(key))continue;const run=await runRoleChannelCell(arm,seed);runs.push(run);done.add(key);write(runs);console.log(`done ${key} calls=${run.calls} score=${run.meanScore.toFixed(3)} hh=${run.mechanism.hhSwaps}/${run.mechanism.hhMeetings} ehg=${run.mechanism.easyToHardGifts}/${run.mechanism.ehGiftOpportunities}`);}write(runs);const final=buildRoleChannelReport(runs,LLM_CONFIG.model,bracketValidity());console.log(`verdict ${final.verdict}`);if(final.verdict==="AWAITING POST-FLIGHT")console.log("Run provider-health post-flight, then rerun this command to finalize with zero additional target calls.");console.log(JSON.stringify({byArm:final.byArm,effects:final.effects,gates:final.gates,integrity:final.integrity,providerBracket:final.providerBracket},null,2));
