import { existsSync,mkdirSync,readFileSync,writeFileSync } from "node:fs";
import { LLM_CONFIG,hasChatApiKey } from "./llm.ts";
import { runSourceValidityBlock } from "./source-validity-gating-execution.ts";
import { SOURCE_VALIDITY_ARMS,SOURCE_VALIDITY_CASES,buildSourceValidityReport,sourceValidityOrder,sourceValidityPrompt,type SourceValidityRecord,type SourceValidityReport } from "./source-validity-gating.ts";
const DATA="src/data/source-validity-gating.json",PUBLIC="public/data/source-validity-gating.json";
function load():SourceValidityRecord[]{if(!existsSync(DATA))return[];const r=JSON.parse(readFileSync(DATA,"utf8")) as SourceValidityReport;if(r.model!==LLM_CONFIG.model)throw new Error(`existing source-validity data uses ${r.model}, current=${LLM_CONFIG.model}`);return r.records;}
function write(rs:SourceValidityRecord[]):void{mkdirSync("src/data",{recursive:true});mkdirSync("public/data",{recursive:true});const s=JSON.stringify(buildSourceValidityReport(rs,LLM_CONFIG.model),null,2);writeFileSync(DATA,s);writeFileSync(PUBLIC,s);}
function dry():void{const item=SOURCE_VALIDITY_CASES[9]!;for(const arm of SOURCE_VALIDITY_ARMS)console.log(`\n=== ${arm} ===\n${sourceValidityPrompt(arm,item)}`);console.log(`\n=== orders ===\n${JSON.stringify(SOURCE_VALIDITY_CASES.map(c=>({block:c.block,q:c.acceptanceProbability,order:sourceValidityOrder(c.block)})),null,2)}`);}
if(process.argv.includes("--dry-run")){dry();process.exit(0);}if(!hasChatApiKey())throw new Error(`${LLM_CONFIG.apiKeyEnv} missing for provider=${LLM_CONFIG.provider}`);const records=load(),complete=new Set(SOURCE_VALIDITY_CASES.filter(c=>SOURCE_VALIDITY_ARMS.every(a=>records.some(r=>r.block===c.block&&r.arm===a))).map(c=>c.block)),partial=SOURCE_VALIDITY_CASES.filter(c=>!complete.has(c.block)&&records.some(r=>r.block===c.block));if(partial.length)throw new Error(`partial block present; preserve records and disclose amendment before resuming: ${partial.map(c=>c.block).join(",")}`);console.log(`resume ${records.length}; source-validity blocks=${SOURCE_VALIDITY_CASES.length}`);for(const item of SOURCE_VALIDITY_CASES){if(complete.has(item.block)){console.log(`skip block=${item.block}`);continue;}const rs=await runSourceValidityBlock(item.block);records.push(...rs);complete.add(item.block);write(records);console.log(`done block=${item.block} q=${item.acceptanceProbability.toFixed(3)}`);}const final=buildSourceValidityReport(records,LLM_CONFIG.model);write(records);console.log(`verdict ${final.verdict}`);for(const arm of SOURCE_VALIDITY_ARMS)console.log(`${arm}: sell=${final.byArm[arm]!.sellRate.toFixed(3)}`);console.log(`pooled-invalid=${final.pooledInvalid?.sellRate.toFixed(3)} accuracy=${final.contractAccuracy?.toFixed(3)}`);
