import assert from "node:assert/strict";import{describe,it}from"node:test";import{SOURCE_VALIDITY_ARMS,SOURCE_VALIDITY_CASES,buildSourceValidityReport,parseSourceValidity,sha256SourceValidity,sourceIsAdmissible,sourceValidityContext,sourceValidityOrder,sourceValidityPrompt,type SourceValidityArm,type SourceValidityRecord}from"./source-validity-gating.ts";
function recordsFor(fn:(a:SourceValidityArm)=>boolean):SourceValidityRecord[]{return SOURCE_VALIDITY_CASES.flatMap(c=>sourceValidityOrder(c.block).map((arm,i)=>({block:c.block,arm,position:i+1,promptHash:sha256SourceValidity(sourceValidityPrompt(arm,c)),context:sourceValidityContext(arm,c),sell:fn(arm)})));}
describe("typed source-validity gating",()=>{
  it("uses 18 above-threshold cases",()=>{assert.equal(SOURCE_VALIDITY_CASES.length,18);for(const c of SOURCE_VALIDITY_CASES){assert.ok(c.acceptanceProbability>c.breakEvenProbability);assert.ok(c.acceptedMarkIncrement*c.acceptanceProbability-c.keepCheckValue>0);}});
  it("balances all nine positions and pairwise precedence",()=>{for(const a of SOURCE_VALIDITY_ARMS)assert.deepEqual([0,1,2,3,4,5,6,7,8].map(p=>SOURCE_VALIDITY_CASES.filter(c=>sourceValidityOrder(c.block)[p]===a).length),Array(9).fill(2));for(const a of SOURCE_VALIDITY_ARMS)for(const b of SOURCE_VALIDITY_ARMS)if(a!==b)assert.equal(SOURCE_VALIDITY_CASES.filter(c=>sourceValidityOrder(c.block).indexOf(a)<sourceValidityOrder(c.block).indexOf(b)).length,9);});
  it("holds numbers fixed and changes only validity metadata",()=>{const c=SOURCE_VALIDITY_CASES[0]!,trusted=sourceValidityContext("pass-current-match",c);for(const a of SOURCE_VALIDITY_ARMS.slice(2)){const x=sourceValidityContext(a,c);assert.equal(x.typedObject.acceptanceProbability,trusted.typedObject.acceptanceProbability);assert.equal(x.typedObject.expectedNetSell,trusted.typedObject.expectedNetSell);}assert.doesNotMatch(sourceValidityPrompt("pass-current-match",c),/recommendedAction/);});
  it("defines only the fully valid arm as admissible and parses strictly",()=>{for(const a of SOURCE_VALIDITY_ARMS)assert.equal(sourceIsAdmissible(a),a==="pass-current-match");assert.equal(parseSourceValidity('{"sell":true}'),true);assert.throws(()=>parseSourceValidity('{"sell":1}'),/schema/);assert.throws(()=>parseSourceValidity('{"sell":true,"why":"x"}'),/schema/);});
  it("supports a perfect conjunction gate",()=>{const r=buildSourceValidityReport(recordsFor(a=>sourceIsAdmissible(a)),"test");assert.equal(r.verdict,"SOURCE VALIDITY GATE SUPPORTED");assert.equal(r.contractAccuracy,1);assert.equal(r.pooledInvalid?.sellRate,0);assert.equal(r.contrasts.validationVeto?.exactUpperP,1/2**18);assert.ok(r.integrity.orderBalanced&&r.integrity.pairwisePrecedenceBalanced);});
  it("separates single-axis and multiple gate failures",()=>{const v=buildSourceValidityReport(recordsFor(a=>a==="pass-current-match"||a==="fail-current-match"),"test");assert.equal(v.verdict,"VALIDATION LABEL NOT GATED");const m=buildSourceValidityReport(recordsFor(a=>a!=="history-only"),"test");assert.equal(m.verdict,"MULTIPLE SOURCE GATES FAIL");});
  it("rejects corrupted stored context",()=>{const rs=recordsFor(()=>false);rs[0]!.context.recentHistory.slots[0]="ACCEPTED" as never;assert.throws(()=>buildSourceValidityReport(rs,"test"),/context mismatch/);});
});
