import { createHash } from "node:crypto";

export const SOURCE_VALIDITY_ARMS = [
  "history-only",
  "pass-current-match",
  "fail-current-match",
  "pass-expired-match",
  "pass-current-mismatch",
  "fail-expired-match",
  "fail-current-mismatch",
  "pass-expired-mismatch",
  "fail-expired-mismatch",
] as const;
export type SourceValidityArm = (typeof SOURCE_VALIDITY_ARMS)[number];

export type SourceValidityCase = { block:number; acceptanceProbability:number; keepCheckValue:0.5; acceptedMarkIncrement:1.83; breakEvenProbability:number };
export const SOURCE_VALIDITY_CASES:readonly SourceValidityCase[]=Array.from({length:18},(_,i)=>({block:i+1,acceptanceProbability:Math.round((0.70+0.25*i/17)*1e6)/1e6,keepCheckValue:0.5 as const,acceptedMarkIncrement:1.83 as const,breakEvenProbability:0.5/1.83}));

type ValidatorStatus="PASS"|"FAIL"|"WITHHELD";
type TemporalScope="CURRENT"|"EXPIRED"|"WITHHELD";
type PopulationScope="MATCH"|"MISMATCH"|"WITHHELD";
export type SourceValidityContext={
  caseId:string;
  payoff:{keepCheckValue:0.5;acceptedMarkIncrement:1.83;exactlyOneFutureUseOpportunity:true};
  recentHistory:{status:"PRESENT";source:"own-K4-recent-meetings";slots:["DECLINED","DECLINED","DECLINED","DECLINED"];note:string};
  admissibilityContract:{rule:"USE_TYPED_NUMBERS_IFF_ALL_THREE_SCOPE_CHECKS_PASS";required:{validatorStatus:"PASS";temporalScope:"CURRENT";populationScope:"MATCH"};invalidAction:"IGNORE_TYPED_NUMERIC_FIELDS_AND_USE_FIRSTHAND_HISTORY"};
  typedObject:{status:"PRESENT"|"WITHHELD";validatorStatus:ValidatorStatus;temporalScope:TemporalScope;populationScope:PopulationScope;source:"external-typed-population-estimate";acceptanceProbability:number|null;markExpectedValue:number|null;expectedNetSell:number|null};
};
export type SourceValidityRecord={block:number;arm:SourceValidityArm;position:number;promptHash:string;context:SourceValidityContext;sell:boolean};
export type SourceValidityRate={n:number;sell:number;sellRate:number;rejectRate:number};
export type SourceValidityContrast={n:number;mean:number;positive:number;negative:number;ties:number;exactUpperP:number|null;values:Array<{block:number;delta:number}>};
export type SourceValidityReport={
  study:"VBE-E-SVG-SOURCE-VALIDITY-GATING";status:"PROJECT-INTERNAL PROSPECTIVE DIAGNOSTIC — NOT EXTERNALLY REGISTERED";frozenProtocol:"VBE-source-validity-gating-protocol.md";model:string;cases:readonly SourceValidityCase[];records:SourceValidityRecord[];calls:number;completeBlocks:number;
  byArm:Partial<Record<SourceValidityArm,SourceValidityRate>>;contrasts:{trustedMinusHistory:SourceValidityContrast|null;validationVeto:SourceValidityContrast|null;temporalVeto:SourceValidityContrast|null;populationVeto:SourceValidityContrast|null};
  pooledInvalid:{n:number;sell:number;sellRate:number}|null;contractAccuracy:number|null;
  gates:{historyReject:boolean;trustedSell:boolean;validationVeto:boolean;temporalVeto:boolean;populationVeto:boolean;invalidPool:boolean;contractAccuracy:boolean};
  integrity:{expectedCalls:162;retainedCalls:number;failedCallsRetained:0;casesValid:boolean;promptsValid:boolean;schemasValid:boolean;orderBalanced:boolean;pairwisePrecedenceBalanced:boolean};
  verdict:"INCOMPLETE"|"INVALID"|"HISTORY BASELINE FAILURE"|"TYPED OBJECT NOT CONSUMED"|"VALIDATION LABEL NOT GATED"|"TEMPORAL SCOPE NOT GATED"|"POPULATION SCOPE NOT GATED"|"MULTIPLE SOURCE GATES FAIL"|"SOURCE VALIDITY GATE SUPPORTED";caveat:string;generatedAt:string;
};

const BASE=[...SOURCE_VALIDITY_ARMS]; const REVERSE=[...BASE].reverse();
function rotate<T>(xs:readonly T[],n:number):T[]{return [...xs.slice(n),...xs.slice(0,n)];}
export function sourceValidityOrder(block:number):readonly SourceValidityArm[]{if(!Number.isInteger(block)||block<1||block>18)throw new Error(`invalid source-validity block ${block}`);return block<=9?rotate(BASE,block-1):rotate(REVERSE,block-10);}
function flags(arm:SourceValidityArm):{present:boolean;validatorStatus:ValidatorStatus;temporalScope:TemporalScope;populationScope:PopulationScope}{if(arm==="history-only")return{present:false,validatorStatus:"WITHHELD",temporalScope:"WITHHELD",populationScope:"WITHHELD"};const [v,t,p]=arm.split("-");return{present:true,validatorStatus:v==="pass"?"PASS":"FAIL",temporalScope:t==="current"?"CURRENT":"EXPIRED",populationScope:p==="match"?"MATCH":"MISMATCH"};}
function round6(n:number):number{return Math.round(n*1e6)/1e6;}
export function sourceValidityContext(arm:SourceValidityArm,item:SourceValidityCase):SourceValidityContext{const f=flags(arm);return{caseId:`SVG-${String(item.block).padStart(2,"0")}`,payoff:{keepCheckValue:0.5,acceptedMarkIncrement:1.83,exactlyOneFutureUseOpportunity:true},recentHistory:{status:"PRESENT",source:"own-K4-recent-meetings",slots:["DECLINED","DECLINED","DECLINED","DECLINED"],note:"four firsthand recent outcomes under the current protocol and population"},admissibilityContract:{rule:"USE_TYPED_NUMBERS_IFF_ALL_THREE_SCOPE_CHECKS_PASS",required:{validatorStatus:"PASS",temporalScope:"CURRENT",populationScope:"MATCH"},invalidAction:"IGNORE_TYPED_NUMERIC_FIELDS_AND_USE_FIRSTHAND_HISTORY"},typedObject:{status:f.present?"PRESENT":"WITHHELD",validatorStatus:f.validatorStatus,temporalScope:f.temporalScope,populationScope:f.populationScope,source:"external-typed-population-estimate",acceptanceProbability:f.present?item.acceptanceProbability:null,markExpectedValue:f.present?round6(item.acceptedMarkIncrement*item.acceptanceProbability):null,expectedNetSell:f.present?round6(item.acceptedMarkIncrement*item.acceptanceProbability-item.keepCheckValue):null}};}
export function sourceValidityPrompt(arm:SourceValidityArm,item:SourceValidityCase):string{const c=sourceValidityContext(arm,item);return`ONE-SHOT SOURCE-GATED MARK DECISION. You are an Easy seller maximizing your own expected score. Keeping the leftover check now is worth exactly 0.50. Selling gives up 0.50 and receives one mark. There is exactly one later opportunity to spend it; acceptance adds 1.83 expected score relative to your own check, rejection adds 0. No other payoff, resale, discounting, or hidden consequence exists.\n\nSOURCE CONTRACT: A typed object's numeric fields are admissible for this current decision if and only if validatorStatus is PASS, temporalScope is CURRENT, and populationScope is MATCH. If any check fails, ignore all typed numeric fields and use the current firsthand history. WITHHELD is absence, not negative evidence.\n\nCONTEXT:\n${JSON.stringify(c)}\n\nChoose whether to sell the current check for one mark. Do not report reasoning. Return JSON only: {"sell":true|false}`;}
export function parseSourceValidity(text:string):boolean{const m=text.match(/\{[\s\S]*\}/);if(!m)throw new Error("missing action JSON object");const o=JSON.parse(m[0]) as Record<string,unknown>;if(JSON.stringify(Object.keys(o))!==JSON.stringify(["sell"])||typeof o.sell!=="boolean")throw new Error("action fields do not match schema");return o.sell;}
export function sha256SourceValidity(text:string):string{return createHash("sha256").update(text).digest("hex");}
export function sourceIsAdmissible(arm:SourceValidityArm):boolean{return arm==="pass-current-match";}
function completeBlocks(rs:readonly SourceValidityRecord[]):number[]{return SOURCE_VALIDITY_CASES.filter(c=>{const x=rs.filter(r=>r.block===c.block);return x.length===9&&new Set(x.map(r=>r.arm)).size===9;}).map(c=>c.block);}
function avg(xs:readonly number[]):number{return xs.reduce((a,b)=>a+b,0)/xs.length;} function choose(n:number,k:number):number{let z=1;for(let i=1;i<=k;i++)z=z*(n-k+i)/i;return z;}function exactUpper(pos:number,neg:number):number|null{const n=pos+neg;if(!n)return null;let z=0;for(let k=pos;k<=n;k++)z+=choose(n,k);return z/2**n;}
function row(rs:readonly SourceValidityRecord[],b:number,a:SourceValidityArm):SourceValidityRecord{const r=rs.find(x=>x.block===b&&x.arm===a);if(!r)throw new Error(`missing ${b}|${a}`);return r;}
function contrast(rs:readonly SourceValidityRecord[],bs:readonly number[],l:SourceValidityArm,r:SourceValidityArm):SourceValidityContrast{const values=bs.map(block=>({block,delta:Number(row(rs,block,l).sell)-Number(row(rs,block,r).sell)}));const positive=values.filter(x=>x.delta>0).length,negative=values.filter(x=>x.delta<0).length;return{n:values.length,mean:avg(values.map(x=>x.delta)),positive,negative,ties:values.length-positive-negative,exactUpperP:exactUpper(positive,negative),values};}
function validate(rs:readonly SourceValidityRecord[]):void{const seen=new Set<string>();for(const r of rs){const item=SOURCE_VALIDITY_CASES[r.block-1];if(!item||!SOURCE_VALIDITY_ARMS.includes(r.arm))throw new Error("unexpected record");const k=`${r.block}|${r.arm}`;if(seen.has(k))throw new Error("duplicate record");seen.add(k);if(r.position!==sourceValidityOrder(r.block).indexOf(r.arm)+1)throw new Error("position mismatch");const c=sourceValidityContext(r.arm,item);if(JSON.stringify(r.context)!==JSON.stringify(c))throw new Error("context mismatch");const p=sourceValidityPrompt(r.arm,item);if(r.promptHash!==sha256SourceValidity(p))throw new Error("prompt hash mismatch");parseSourceValidity(JSON.stringify({sell:r.sell}));}}
export function buildSourceValidityReport(input:SourceValidityRecord[],model:string):SourceValidityReport{validate(input);const records=[...input].sort((a,b)=>a.block-b.block||a.position-b.position),bs=completeBlocks(records),complete=bs.length===18;const byArm:SourceValidityReport["byArm"]={};for(const a of SOURCE_VALIDITY_ARMS){const x=records.filter(r=>r.arm===a);if(x.length){const sell=x.filter(r=>r.sell).length;byArm[a]={n:x.length,sell,sellRate:sell/x.length,rejectRate:1-sell/x.length};}}
  const cs={trustedMinusHistory:complete?contrast(records,bs,"pass-current-match","history-only"):null,validationVeto:complete?contrast(records,bs,"pass-current-match","fail-current-match"):null,temporalVeto:complete?contrast(records,bs,"pass-current-match","pass-expired-match"):null,populationVeto:complete?contrast(records,bs,"pass-current-match","pass-current-mismatch"):null};const invalid=records.filter(r=>r.arm!=="history-only"&&!sourceIsAdmissible(r.arm));const pooledInvalid=complete?{n:invalid.length,sell:invalid.filter(r=>r.sell).length,sellRate:invalid.filter(r=>r.sell).length/invalid.length}:null;const contractAccuracy=complete?avg(records.map(r=>Number(r.sell===sourceIsAdmissible(r.arm)))):null;
  const axis=(a:SourceValidityArm,c:SourceValidityContrast|null)=>Boolean(complete&&byArm[a]!.sellRate<=0.15&&c&&c.mean>=0.5&&c.exactUpperP!==null&&c.exactUpperP<=0.025);const gates={historyReject:Boolean(complete&&byArm["history-only"]!.rejectRate>=0.85),trustedSell:Boolean(complete&&byArm["pass-current-match"]!.sellRate>=0.85),validationVeto:axis("fail-current-match",cs.validationVeto),temporalVeto:axis("pass-expired-match",cs.temporalVeto),populationVeto:axis("pass-current-mismatch",cs.populationVeto),invalidPool:Boolean(complete&&pooledInvalid!.sellRate<=0.15),contractAccuracy:Boolean(complete&&contractAccuracy!>=0.90)};
  const orderBalanced=complete&&SOURCE_VALIDITY_ARMS.every(a=>[0,1,2,3,4,5,6,7,8].every(p=>SOURCE_VALIDITY_CASES.filter(c=>sourceValidityOrder(c.block)[p]===a).length===2));const pairwisePrecedenceBalanced=complete&&SOURCE_VALIDITY_ARMS.every(a=>SOURCE_VALIDITY_ARMS.every(b=>a===b||SOURCE_VALIDITY_CASES.filter(c=>sourceValidityOrder(c.block).indexOf(a)<sourceValidityOrder(c.block).indexOf(b)).length===9));const integrity={expectedCalls:162 as const,retainedCalls:records.length,failedCallsRetained:0 as const,casesValid:SOURCE_VALIDITY_CASES.every(c=>c.acceptanceProbability>c.breakEvenProbability),promptsValid:true,schemasValid:true,orderBalanced,pairwisePrecedenceBalanced};let verdict:SourceValidityReport["verdict"]="INCOMPLETE";if(complete){if(!Object.values(integrity).every(v=>typeof v==="number"?true:Boolean(v)))verdict="INVALID";else if(!gates.historyReject)verdict="HISTORY BASELINE FAILURE";else if(!gates.trustedSell)verdict="TYPED OBJECT NOT CONSUMED";else{const failed=[gates.validationVeto?null:"v",gates.temporalVeto?null:"t",gates.populationVeto?null:"p"].filter(Boolean);if(failed.length===0&&gates.invalidPool&&gates.contractAccuracy)verdict="SOURCE VALIDITY GATE SUPPORTED";else if(failed.length===1&&failed[0]==="v")verdict="VALIDATION LABEL NOT GATED";else if(failed.length===1&&failed[0]==="t")verdict="TEMPORAL SCOPE NOT GATED";else if(failed.length===1&&failed[0]==="p")verdict="POPULATION SCOPE NOT GATED";else verdict="MULTIPLE SOURCE GATES FAIL";}}
  return{study:"VBE-E-SVG-SOURCE-VALIDITY-GATING",status:"PROJECT-INTERNAL PROSPECTIVE DIAGNOSTIC — NOT EXTERNALLY REGISTERED",frozenProtocol:"VBE-source-validity-gating-protocol.md",model,cases:SOURCE_VALIDITY_CASES,records,calls:records.length,completeBlocks:bs.length,byArm,contrasts:cs,pooledInvalid,contractAccuracy,gates,integrity,verdict,caveat:"This sealed factorial identifies action-level adherence to an explicit source-admissibility contract while invalid numbers remain visible. It does not validate the validator, authenticate labels, establish latent belief, prove cryptographic provenance, or establish transfer to long-context environments or other models.",generatedAt:new Date().toISOString()};}
