import { runPopulationAsyncPaired } from "./env.ts";
import { grokChat, parseProposal } from "./llm.ts";
import { DEFAULT_PARAMS } from "./params.ts";
import { meetingPrompt, RULES } from "./prompts.ts";
import type { AgentState, Proposal } from "./types.ts";
import { SEMANTIC_BOUNDARY_ARMS,SEMANTIC_BOUNDARY_SEEDS,semanticBoundaryNotice,semanticBoundaryOrder,semanticBoundaryRunSummary,strictSemanticBoundaryAction,type SemanticBoundaryArm,type SemanticBoundaryRun } from "./welfare-semantic-boundary.ts";

export async function runSemanticBoundaryCell(arm:SemanticBoundaryArm,seed:number):Promise<SemanticBoundaryRun>{let calls=0;const decide=async(me:AgentState,partner:AgentState,t:number):Promise<Proposal>=>{calls++;const response=await grokChat({prompt:meetingPrompt(me,partner,t,DEFAULT_PARAMS,"label",semanticBoundaryNotice(arm)),system:RULES,maxTokens:64,temperature:0,json:true});if(!response.ok)throw new Error(`semantic-boundary ${arm} seed=${seed} t=${t} agent=${me.id}: ${response.error}`);const invalid=strictSemanticBoundaryAction(response.text);if(invalid)throw new Error(`semantic-boundary ${arm} seed=${seed} t=${t} agent=${me.id}: ${invalid}; raw=${response.text.slice(0,180)}`);return parseProposal(response.text);};const result=await runPopulationAsyncPaired(seed,decide,DEFAULT_PARAMS,true);return{seed,arm,position:semanticBoundaryOrder(seed).indexOf(arm)+1,calls,apiFails:0,parseFails:0,robotCalls:0,notice:semanticBoundaryNotice(arm),...semanticBoundaryRunSummary(result),result};}

export async function semanticBoundaryCallArithmetic():Promise<{perArm:number;targetCalls:number;bySeed:Array<{seed:number;calls:number}>}>{const bySeed:Array<{seed:number;calls:number}>=[];for(const seed of SEMANTIC_BOUNDARY_SEEDS){let calls=0;await runPopulationAsyncPaired(seed,async()=>{calls++;return{giveCheck:false,giveChits:0,requireChit:false};},DEFAULT_PARAMS,true);bySeed.push({seed,calls});}const perArm=bySeed.reduce((s,x)=>s+x.calls,0);return{perArm,targetCalls:perArm*SEMANTIC_BOUNDARY_ARMS.length,bySeed};}
export async function printSemanticBoundaryDryRun():Promise<void>{const arithmetic=await semanticBoundaryCallArithmetic(),me:AgentState={id:2,type:"E",checks:1,chits:0,score:20,solved:true,receivedFrom:null,memory:[]},partner:AgentState={...me,id:5,type:"H",chits:1,solved:false};console.log(`# ${SEMANTIC_BOUNDARY_SEEDS.length} blocks × ${SEMANTIC_BOUNDARY_ARMS.length} arms; calls=${arithmetic.targetCalls}; per-arm=${arithmetic.perArm}`);console.log(`by-seed=${arithmetic.bySeed.map(x=>`${x.seed}:${x.calls}`).join(",")}`);for(const arm of SEMANTIC_BOUNDARY_ARMS)console.log(`\n=== ${arm} ===\n${meetingPrompt(me,partner,12,DEFAULT_PARAMS,"label",semanticBoundaryNotice(arm))}`);}
