import { runPopulationAsyncPaired } from "./env.ts";
import { grokChat, parseProposal } from "./llm.ts";
import { DEFAULT_PARAMS } from "./params.ts";
import { meetingPrompt, RULES } from "./prompts.ts";
import type { AgentState, Proposal } from "./types.ts";
import { executeRoleChannel,roleChannelNotice,roleChannelOrder,roleChannelRunSummary,strictRoleChannelAction,summarizeOriginalMechanism,type RoleChannelArm,type RoleChannelRun,type RoleChannelTrace } from "./welfare-role-channel.ts";

export async function runRoleChannelCell(arm:RoleChannelArm,seed:number):Promise<RoleChannelRun>{let calls=0;const trace:RoleChannelTrace[]=[];const decide=async(me:AgentState,partner:AgentState,t:number):Promise<Proposal>=>{calls++;const response=await grokChat({prompt:meetingPrompt(me,partner,t,DEFAULT_PARAMS,"label",roleChannelNotice(arm)),system:RULES,maxTokens:64,temperature:0,json:true});if(!response.ok)throw new Error(`role-channel ${arm} seed=${seed} t=${t} agent=${me.id}: ${response.error}`);const invalid=strictRoleChannelAction(response.text);if(invalid)throw new Error(`role-channel ${arm} seed=${seed} t=${t} agent=${me.id}: ${invalid}; raw=${response.text.slice(0,180)}`);const original=parseProposal(response.text),out=executeRoleChannel(arm,me.type,partner.type,me.checks,original);trace.push({t,meId:me.id,partnerId:partner.id,meType:me.type,partnerType:partner.type,meChecks:me.checks,meChits:me.chits,partnerChecks:partner.checks,partnerChits:partner.chits,original,executed:out.proposal,eligible:out.eligible,blocked:out.blocked});return out.proposal;};const result=await runPopulationAsyncPaired(seed,decide,DEFAULT_PARAMS,true);trace.sort((a,b)=>a.t-b.t||a.meId-b.meId||a.partnerId-b.partnerId);const transformFidelity=trace.every(x=>{const q=executeRoleChannel(arm,x.meType,x.partnerType,x.meChecks,x.original);return q.eligible===x.eligible&&q.blocked===x.blocked&&JSON.stringify(q.proposal)===JSON.stringify(x.executed);});return{seed,arm,position:roleChannelOrder(seed).indexOf(arm)+1,calls,apiFails:0,parseFails:0,robotCalls:0,notice:roleChannelNotice(arm),trace,transformFidelity,...roleChannelRunSummary(result),originalMechanism:summarizeOriginalMechanism(trace),result};}

export function printRoleChannelDryRun():void{const me:AgentState={id:2,type:"E",checks:1,chits:0,score:20,solved:true,receivedFrom:null,memory:[]},partner:AgentState={...me,id:5,type:"H",chits:1,solved:false};for(const arm of ROLE_CHANNEL_ARMS_LOCAL)console.log(`\n=== ${arm} ===\n${meetingPrompt(me,partner,12,DEFAULT_PARAMS,"label",roleChannelNotice(arm))}`);for(const arm of ["gift-hh-blocked","gift-eh-gift-blocked"] as const)for(const [a,b] of [[{...me,type:"H" as const},partner],[me,partner]] as const){const original={giveCheck:true,giveChits:0,requireChit:false};console.log(`\n=== transform ${arm} ${a.type}-${b.type} ===\n${JSON.stringify({original,...executeRoleChannel(arm,a.type,b.type,a.checks,original)})}`);}}
const ROLE_CHANNEL_ARMS_LOCAL=["neutral-standard","gift-standard","gift-hh-blocked","gift-eh-gift-blocked"] as const;
