import assert from "node:assert/strict";
import { describe,it } from "node:test";
import { CROWDING_ARMS,CROWDING_BRIDGE_ARMS,CROWDING_BRIDGE_BLOCKS,CROWDING_SEEDS,CROWDING_TARGET_CALLS,buildCrowdingReport,crowdingBridgeCases,crowdingBridgeOrder,crowdingNotice,crowdingOrder,crowdingVerdict,sha256Crowding,strictCrowdingAction } from "./welfare-crowding-out.ts";

describe("welfare crowding-out replication",()=>{
  it("uses 18 unique fresh seeds, balances two-arm order, and freezes call arithmetic",()=>{assert.equal(new Set(CROWDING_SEEDS).size,18);assert.equal(CROWDING_TARGET_CALLS,2728);for(const arm of CROWDING_ARMS)assert.deepEqual([0,1].map(position=>CROWDING_SEEDS.filter(seed=>crowdingOrder(seed)[position]===arm).length),[9,9]);});
  it("preserves the two historical speech packages exactly",()=>{assert.match(crowdingNotice("money-talk"),/mark is accepted as payment/);assert.match(crowdingNotice("gift-talk"),/without requiring a mark/);assert.match(crowdingNotice("gift-talk"),/Do not sell/);});
  it("freezes 12 byte-exact, directionally mixed historical bridge prompts",()=>{const cases=crowdingBridgeCases();assert.equal(cases.length,12);assert.deepEqual([...new Set(cases.map(item=>item.block))], [...CROWDING_BRIDGE_BLOCKS]);for(const item of cases)assert.equal(sha256Crowding(item.prompt),item.historicalPromptHash);for(const arm of CROWDING_BRIDGE_ARMS)assert.equal(cases.filter(item=>item.arm===arm).length,4);assert.equal(cases.filter(item=>item.historicalBuy).length,8);assert.equal(cases.filter(item=>!item.historicalBuy).length,4);});
  it("rotates bridge positions without changing block contents",()=>{for(const block of CROWDING_BRIDGE_BLOCKS)assert.deepEqual(new Set(crowdingBridgeOrder(block)),new Set(CROWDING_BRIDGE_ARMS));for(const arm of CROWDING_BRIDGE_ARMS)assert.deepEqual([0,1,2].map(position=>CROWDING_BRIDGE_BLOCKS.filter(block=>crowdingBridgeOrder(block)[position]===arm).length).sort(),[1,1,2]);});
  it("rejects permissive action schemas",()=>{assert.equal(strictCrowdingAction('{"giveCheck":true,"giveChits":0,"requireChit":false}'),null);assert.ok(strictCrowdingAction('{"giveCheck":true,"giveChits":0,"requireChit":false,"x":1}'));assert.ok(strictCrowdingAction("not json"));});
  it("accepts the parser's inert optional fields while preserving a strict raw bridge schema",()=>{const item=crowdingBridgeCases()[0]!;const raw='{"giveCheck":false,"giveChits":1,"requireChit":false}';const report=buildCrowdingReport([],[{block:item.block,arm:item.arm,position:crowdingBridgeOrder(item.block).indexOf(item.arm)+1,sourceStudy:item.sourceStudy,sourceBlock:item.sourceBlock,promptHash:sha256Crowding(item.prompt),historicalPromptHash:item.historicalPromptHash,historicalBuy:item.historicalBuy,rawResponse:raw,rawResponseSha256:sha256Crowding(raw),proposal:{giveCheck:false,giveChits:1,requireChit:false,forfeit:0,pAccept:undefined,pSecond:undefined},buy:true,provider:{responseId:"r",returnedModel:"deepseek-flash",created:0,systemFingerprint:"fp",usage:{promptTokens:1,completionTokens:1,totalTokens:2,promptCacheHitTokens:0,promptCacheMissTokens:1},headers:{},attempt:1}}],"deepseek-flash");assert.equal(report.bridgeRecords.length,1);assert.equal(report.verdict,"INCOMPLETE");});
  it("keeps bridge outside the verdict and post-flight inside it",()=>{assert.equal(crowdingVerdict(true,true,true,true,true),"WELFARE CROWDING-OUT PACKAGE REPLICATED");assert.equal(crowdingVerdict(true,true,true,true,false),"WELFARE CONTRAST WITHOUT JOINT BEHAVIORAL SUBSTITUTION");assert.equal(crowdingVerdict(true,true,true,false,true),"NO WELFARE PACKAGE EFFECT");assert.equal(crowdingVerdict(true,true,null,true,true),"AWAITING POST-FLIGHT");assert.equal(crowdingVerdict(false,true,null,true,true),"INCOMPLETE");assert.equal(crowdingVerdict(true,false,true,true,true),"INVALID");assert.equal(crowdingVerdict(true,true,false,true,true),"INVALID");});
});
