import assert from "node:assert/strict";
import { describe,it } from "node:test";
import { GIFT_ANNOUNCE } from "./speech.ts";
import { NEUTRAL_ANNOUNCE,ROLE_CHANNEL_ARMS,ROLE_CHANNEL_SEEDS,ROLE_CHANNEL_TARGET_CALLS,channelEligible,executeRoleChannel,roleChannelNotice,roleChannelOrder,roleChannelVerdict,strictRoleChannelAction } from "./welfare-role-channel.ts";

describe("welfare role-generalization channel",()=>{
  it("uses 12 fresh unique seeds and freezes 3x positional plus pairwise balance",()=>{assert.equal(new Set(ROLE_CHANNEL_SEEDS).size,12);assert.equal(ROLE_CHANNEL_TARGET_CALLS,3680);for(const arm of ROLE_CHANNEL_ARMS)assert.deepEqual([0,1,2,3].map(p=>ROLE_CHANNEL_SEEDS.filter(seed=>roleChannelOrder(seed)[p]===arm).length),[3,3,3,3]);for(let i=0;i<ROLE_CHANNEL_ARMS.length;i++)for(let j=i+1;j<ROLE_CHANNEL_ARMS.length;j++)assert.equal(ROLE_CHANNEL_SEEDS.filter(seed=>roleChannelOrder(seed).indexOf(ROLE_CHANNEL_ARMS[i]!)<roleChannelOrder(seed).indexOf(ROLE_CHANNEL_ARMS[j]!)).length,6);});
  it("keeps all three gift prompts byte-identical and separates the neutral reference",()=>{assert.equal(roleChannelNotice("gift-standard"),GIFT_ANNOUNCE);assert.equal(roleChannelNotice("gift-hh-blocked"),GIFT_ANNOUNCE);assert.equal(roleChannelNotice("gift-eh-gift-blocked"),GIFT_ANNOUNCE);assert.equal(roleChannelNotice("neutral-standard"),NEUTRAL_ANNOUNCE);assert.notEqual(NEUTRAL_ANNOUNCE,GIFT_ANNOUNCE);});
  it("suppresses only feasible H-H check-giving in the H-H arm",()=>{const give={giveCheck:true,giveChits:0,requireChit:false},idle={giveCheck:false,giveChits:0,requireChit:false};assert.equal(channelEligible("gift-hh-blocked","H","H",1,give),true);assert.deepEqual(executeRoleChannel("gift-hh-blocked","H","H",1,give).proposal,{giveCheck:false,giveChits:0,requireChit:false});assert.deepEqual(executeRoleChannel("gift-hh-blocked","E","H",1,give).proposal,give);assert.deepEqual(executeRoleChannel("gift-hh-blocked","H","H",0,give).proposal,give);assert.deepEqual(executeRoleChannel("gift-hh-blocked","H","H",1,idle).proposal,idle);});
  it("suppresses only feasible unconditional E-to-H gifts in the E-H arm",()=>{const gift={giveCheck:true,giveChits:0,requireChit:false},sale={giveCheck:true,giveChits:0,requireChit:true};assert.equal(channelEligible("gift-eh-gift-blocked","E","H",1,gift),true);assert.equal(executeRoleChannel("gift-eh-gift-blocked","E","H",1,gift).proposal.giveCheck,false);assert.deepEqual(executeRoleChannel("gift-eh-gift-blocked","E","H",1,sale).proposal,sale);assert.deepEqual(executeRoleChannel("gift-eh-gift-blocked","H","H",1,gift).proposal,gift);assert.deepEqual(executeRoleChannel("gift-eh-gift-blocked","E","H",0,gift).proposal,gift);});
  it("keeps invalid manipulations distinct from substantive nulls",()=>{assert.equal(roleChannelVerdict(false,true,null,true,true,true,true),"INCOMPLETE");assert.equal(roleChannelVerdict(true,false,true,true,true,true,true),"INVALID");assert.equal(roleChannelVerdict(true,true,null,true,true,true,true),"AWAITING POST-FLIGHT");assert.equal(roleChannelVerdict(true,true,true,false,true,true,true),"CHANNEL MANIPULATION NOT VALIDATED");assert.equal(roleChannelVerdict(true,true,true,true,false,true,true),"NO MATERIAL HH EXECUTION-CHANNEL CONTRIBUTION");assert.equal(roleChannelVerdict(true,true,true,true,true,false,true),"HH EXECUTION CHANNEL CONTRIBUTES WITHOUT DOMINANCE");assert.equal(roleChannelVerdict(true,true,true,true,true,true,false),"HH EXECUTION CHANNEL DOMINATES UNDER GIFT TALK");assert.equal(roleChannelVerdict(true,true,true,true,true,true,true),"HH EXECUTION CHANNEL DOMINATES REPLICATED GIFT-TALK WELFARE EFFECT");});
  it("rejects permissive action schemas",()=>{assert.equal(strictRoleChannelAction('{"giveCheck":true,"giveChits":0,"requireChit":false}'),null);assert.ok(strictRoleChannelAction('{"giveCheck":true,"giveChits":0,"requireChit":false,"x":1}'));assert.ok(strictRoleChannelAction("no json"));});
});
